import { Router, type IRouter } from "express";
import healthRouter from "./health";
import booksRouter from "./books";
import videosRouter from "./videos";
import postsRouter from "./posts";
import pointsRouter from "./points";
import gamesRouter from "./games";
import rewardsRouter from "./rewards";
import openaiRouter from "./openai";
import adminRouter from "./admin";
import moderatorRouter from "./moderator";
import authRouter from "./auth";
import academicRouter from "./academic";
import notificationsRouter from "./notifications";
import supportRouter from "./support";
import internalChatRouter from "./internal-chat";
import studentRouter from "./student";
import gamificationRouter from "./gamification";
import gamificationAdminRouter from "./gamification-admin";
import moderationRouter from "./moderation";
import quizRouter from "./quiz";
import unitExamsRouter from "./unit-exams";
import engagementRouter from "./engagement";
import shippingRouter from "./shipping";
import storeRouter from "./store";
import appConfigRouter from "./app-config";

const router: IRouter = Router();

router.use(healthRouter);
router.use(booksRouter);
router.use(videosRouter);
router.use(postsRouter);
router.use(pointsRouter);
router.use(gamesRouter);
router.use(rewardsRouter);
router.use(openaiRouter);
router.use(adminRouter);
router.use(moderatorRouter);
router.use(authRouter);
router.use(academicRouter);
router.use(notificationsRouter);
router.use(supportRouter);
router.use(internalChatRouter);
router.use(studentRouter);
router.use(gamificationRouter);
router.use(gamificationAdminRouter);
router.use(moderationRouter);
router.use(quizRouter);
router.use(unitExamsRouter);
router.use(engagementRouter);
router.use(shippingRouter);
router.use(storeRouter);
router.use(appConfigRouter);

export default router;
